[versions]
agp = "8.11.2"
appcompat = "1.6.1"
core = "1.12.0"
espressoCore = "3.5.1"
junit = "4.13.2"
junitVersion = "1.1.5"
lifecycle = "2.6.2"
material = "1.11.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
core = { group = "androidx.core", name = "core", version.ref = "core" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "lifecycle" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
